// Code generated by ogen, DO NOT EDIT.

package fabricv1server

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AllocateFloatingIP implements allocate-floating-ip operation.
//
// Creates a Billing order, including for metered pricing. The price must belong to the resource’s
// Billing Plan; applicable contract pricing is resolved by Billing. Technical capacity is checked
// before sellable quota is reserved. Provisioning continues automatically after payment; do not submit
// a new purchase after paying. Reuse the original idempotency key after an uncertain response.
//
// POST /api/v1/floating-ips
func (UnimplementedHandler) AllocateFloatingIP(ctx context.Context, req *AllocateFloatingIPRequestBody) (r *PlacedOrder, _ error) {
	return r, ht.ErrNotImplemented
}

// BindFloatingIP implements bind-floating-ip operation.
//
// Bind a floating IP to a network interface.
//
// PUT /api/v1/floating-ips/{floatingIpId}/binding
func (UnimplementedHandler) BindFloatingIP(ctx context.Context, req *BindFloatingIPRequestBody, params BindFloatingIPParams) (r *FloatingIPResource, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePort implements create-port operation.
//
// The new network interface is not attached to any instance. Primary network interfaces are not
// created here; they are created with the instance.
//
// POST /api/v1/ports
func (UnimplementedHandler) CreatePort(ctx context.Context, req *CreatePortRequestBody) (r *PortResource, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePrivateNetwork implements create-private-network operation.
//
// Starts creation of a network, router and default security group. The returned resource is
// `provisioning` until all three are ready. Reuse the same idempotency key after an uncertain
// response.
//
// POST /api/v1/private-networks
func (UnimplementedHandler) CreatePrivateNetwork(ctx context.Context, req *CreatePrivateNetworkRequestBody) (r *PrivateNetworkResource, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateRoute implements create-route operation.
//
// Three forms that would sever connectivity are rejected: a destination of `0.0.0.0/0`, which
// overrides the default route and takes every floating IP offline immediately; a destination equal to
// the CIDR of a subnet, which overrides its directly connected route; and a next hop equal to the
// gateway of a subnet, which points back at the router itself.
//
// POST /api/v1/private-networks/{privateNetworkId}/routes
func (UnimplementedHandler) CreateRoute(ctx context.Context, req *CreateRouteRequestBody, params CreateRouteParams) (r *RouteResource, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSecurityGroup implements create-security-group operation.
//
// A new security group carries one rule, permitting ICMP fragmentation-needed messages (type 3, code
// 4). Without it path MTU discovery fails, which presents as connections that establish and then stall
// on large packets.
//
// POST /api/v1/security-groups
func (UnimplementedHandler) CreateSecurityGroup(ctx context.Context, req *CreateSecurityGroupRequestBody) (r *SecurityGroupResource, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSecurityGroupRule implements create-security-group-rule operation.
//
// Adding an identical rule twice is rejected. For that comparison `0.0.0.0/0`, `::/0` and an omitted
// value are treated as equivalent.
//
// POST /api/v1/security-groups/{securityGroupId}/rules
func (UnimplementedHandler) CreateSecurityGroupRule(ctx context.Context, req *CreateSecurityRuleRequestBody, params CreateSecurityGroupRuleParams) (r *SecurityRuleResource, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSubnet implements create-subnet operation.
//
// Create a subnet.
//
// POST /api/v1/private-networks/{privateNetworkId}/subnets
func (UnimplementedHandler) CreateSubnet(ctx context.Context, req *CreateSubnetRequestBody, params CreateSubnetParams) (r *SubnetResource, _ error) {
	return r, ht.ErrNotImplemented
}

// DeletePort implements delete-port operation.
//
// The primary network interface cannot be deleted on its own, as it is released with the instance. A
// network interface still attached to an instance cannot be deleted either.
//
// DELETE /api/v1/ports/{portId}
func (UnimplementedHandler) DeletePort(ctx context.Context, params DeletePortParams) error {
	return ht.ErrNotImplemented
}

// DeletePrivateNetwork implements delete-private-network operation.
//
// Release is rejected while instances or network interfaces remain in the network. IPv6, the router
// and the security groups are released with it.
//
// DELETE /api/v1/private-networks/{privateNetworkId}
func (UnimplementedHandler) DeletePrivateNetwork(ctx context.Context, params DeletePrivateNetworkParams) error {
	return ht.ErrNotImplemented
}

// DeleteRoute implements delete-route operation.
//
// Delete a static route.
//
// DELETE /api/v1/private-networks/{privateNetworkId}/routes/{routeId}
func (UnimplementedHandler) DeleteRoute(ctx context.Context, params DeleteRouteParams) error {
	return ht.ErrNotImplemented
}

// DeleteSecurityGroup implements delete-security-group operation.
//
// The default security group cannot be deleted, as it is released with the private network. A security
// group still referenced by a network interface cannot be deleted either.
//
// DELETE /api/v1/security-groups/{securityGroupId}
func (UnimplementedHandler) DeleteSecurityGroup(ctx context.Context, params DeleteSecurityGroupParams) error {
	return ht.ErrNotImplemented
}

// DeleteSecurityGroupRule implements delete-security-group-rule operation.
//
// Delete a security group rule.
//
// DELETE /api/v1/security-groups/{securityGroupId}/rules/{ruleId}
func (UnimplementedHandler) DeleteSecurityGroupRule(ctx context.Context, params DeleteSecurityGroupRuleParams) error {
	return ht.ErrNotImplemented
}

// DeleteSubnet implements delete-subnet operation.
//
// Deletion is rejected while network interfaces remain in the subnet, or while a static route has a
// next hop inside its CIDR.
//
// DELETE /api/v1/private-networks/{privateNetworkId}/subnets/{subnetId}
func (UnimplementedHandler) DeleteSubnet(ctx context.Context, params DeleteSubnetParams) error {
	return ht.ErrNotImplemented
}

// DisablePrivateNetworkIpv6 implements disable-private-network-ipv6 operation.
//
// A released prefix is not re-allocated immediately.
//
// DELETE /api/v1/private-networks/{privateNetworkId}/ipv6
func (UnimplementedHandler) DisablePrivateNetworkIpv6(ctx context.Context, params DisablePrivateNetworkIpv6Params) error {
	return ht.ErrNotImplemented
}

// EnablePrivateNetworkIpv6 implements enable-private-network-ipv6 operation.
//
// Allocates an IPv6 prefix to the private network. Addresses are assigned to instances by the network
// itself, can be neither requested nor released individually, and consume no public IPv4 address.
//
// If the private network is not yet connected to the internet, connectivity is established as part of
// this call.
//
// POST /api/v1/private-networks/{privateNetworkId}/ipv6
func (UnimplementedHandler) EnablePrivateNetworkIpv6(ctx context.Context, params EnablePrivateNetworkIpv6Params) (r *IPv6ResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAttachment implements get-attachment operation.
//
// Get attachment.
//
// GET /api/v1/attachments/{attachmentId}
func (UnimplementedHandler) GetAttachment(ctx context.Context, params GetAttachmentParams) (r *Attachment, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFloatingIP implements get-floating-ip operation.
//
// Retrieve a floating IP.
//
// GET /api/v1/floating-ips/{floatingIpId}
func (UnimplementedHandler) GetFloatingIP(ctx context.Context, params GetFloatingIPParams) (r *FloatingIPResource, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPort implements get-port operation.
//
// Get port.
//
// GET /api/v1/ports/{portId}
func (UnimplementedHandler) GetPort(ctx context.Context, params GetPortParams) (r *PortResource, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPrivateNetwork implements get-private-network operation.
//
// Retrieve a private network.
//
// GET /api/v1/private-networks/{privateNetworkId}
func (UnimplementedHandler) GetPrivateNetwork(ctx context.Context, params GetPrivateNetworkParams) (r *PrivateNetworkResource, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPrivateNetworkIpv6 implements get-private-network-ipv6 operation.
//
// Retrieve the IPv6 configuration of a private network.
//
// GET /api/v1/private-networks/{privateNetworkId}/ipv6
func (UnimplementedHandler) GetPrivateNetworkIpv6(ctx context.Context, params GetPrivateNetworkIpv6Params) (r *IPv6ResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// GetResourceReclamation implements get-resource-reclamation operation.
//
// Get resource reclamation.
//
// GET /api/v1/resources/{resourceType}/{resourceId}/reclamation
func (UnimplementedHandler) GetResourceReclamation(ctx context.Context, params GetResourceReclamationParams) (r *ReclamationState, _ error) {
	return r, ht.ErrNotImplemented
}

// GetResourceUsage implements get-resource-usage operation.
//
// Get resource usage.
//
// GET /api/v1/resource-usages/{usageId}
func (UnimplementedHandler) GetResourceUsage(ctx context.Context, params GetResourceUsageParams) (r *ResourceUsage, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSecurityGroup implements get-security-group operation.
//
// Retrieve a security group.
//
// GET /api/v1/security-groups/{securityGroupId}
func (UnimplementedHandler) GetSecurityGroup(ctx context.Context, params GetSecurityGroupParams) (r *SecurityGroupResource, _ error) {
	return r, ht.ErrNotImplemented
}

// ListFloatingIps implements list-floating-ips operation.
//
// List floating IPs.
//
// GET /api/v1/floating-ips
func (UnimplementedHandler) ListFloatingIps(ctx context.Context, params ListFloatingIpsParams) (r *FloatingIPListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListOperationLogs implements list-operation-logs operation.
//
// Records every write operation in the project: who performed it, when, on what, and whether it
// succeeded. Read operations are not recorded.
//
// Operations performed by the platform are included, but the individual operator is not disclosed and
// `by_platform` is true. Suspension for non-payment and bans for abuse are examples: the time at which
// an instance was stopped by the platform is needed, whereas the operator is internal information.
//
// Fields such as passwords are replaced with a placeholder as the record is written and never appear
// in `payload`.
//
// GET /api/v1/operation-logs
func (UnimplementedHandler) ListOperationLogs(ctx context.Context, params ListOperationLogsParams) (r *OperationLogListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPortAttachments implements list-port-attachments operation.
//
// Actual attachment state, including operations whose provider outcome is unknown. Use usage_id to
// locate the corresponding blocking claim.
//
// GET /api/v1/ports/{resourceId}/attachments
func (UnimplementedHandler) ListPortAttachments(ctx context.Context, params ListPortAttachmentsParams) (r *AttachmentList, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPorts implements list-ports operation.
//
// List network interfaces.
//
// GET /api/v1/ports
func (UnimplementedHandler) ListPorts(ctx context.Context, params ListPortsParams) (r *PortListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPrivateNetworks implements list-private-networks operation.
//
// List private networks.
//
// GET /api/v1/private-networks
func (UnimplementedHandler) ListPrivateNetworks(ctx context.Context, params ListPrivateNetworksParams) (r *PrivateNetworkListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListResourceUsages implements list-resource-usages operation.
//
// Lists direct consumers, including pending reservations and claims being released. The resource must
// be readable by the caller. Historical released claims are included only when requested.
//
// GET /api/v1/resource-usages
func (UnimplementedHandler) ListResourceUsages(ctx context.Context, params ListResourceUsagesParams) (r *ResourceUsageList, _ error) {
	return r, ht.ErrNotImplemented
}

// ListRoutes implements list-routes operation.
//
// List static routes.
//
// GET /api/v1/private-networks/{privateNetworkId}/routes
func (UnimplementedHandler) ListRoutes(ctx context.Context, params ListRoutesParams) (r *RouteListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListSecurityGroupRules implements list-security-group-rules operation.
//
// List security group rules.
//
// GET /api/v1/security-groups/{securityGroupId}/rules
func (UnimplementedHandler) ListSecurityGroupRules(ctx context.Context, params ListSecurityGroupRulesParams) (r *SecurityRuleListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListSecurityGroups implements list-security-groups operation.
//
// List security groups.
//
// GET /api/v1/security-groups
func (UnimplementedHandler) ListSecurityGroups(ctx context.Context, params ListSecurityGroupsParams) (r *SecurityGroupListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListSubnets implements list-subnets operation.
//
// IPv6 subnets are included, with `ip_version` 6. They are created when IPv6 is enabled and cannot be
// deleted individually.
//
// GET /api/v1/private-networks/{privateNetworkId}/subnets
func (UnimplementedHandler) ListSubnets(ctx context.Context, params ListSubnetsParams) (r *SubnetListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ReleaseFloatingIP implements release-floating-ip operation.
//
// A released address enters a cooldown period before it is allocated again, so that DNS records and
// allow-lists still pointing at it do not break immediately. The same address therefore cannot be
// re-allocated for some time after release. Proceed with care.
//
// DELETE /api/v1/floating-ips/{floatingIpId}
func (UnimplementedHandler) ReleaseFloatingIP(ctx context.Context, params ReleaseFloatingIPParams) error {
	return ht.ErrNotImplemented
}

// RenamePrivateNetwork implements rename-private-network operation.
//
// Changes the display name only. The CIDR, the routes and the internet gateway are immutable.
//
// PATCH /api/v1/private-networks/{privateNetworkId}
func (UnimplementedHandler) RenamePrivateNetwork(ctx context.Context, req *RenamePrivateNetworkRequestBody, params RenamePrivateNetworkParams) (r *PrivateNetworkResource, _ error) {
	return r, ht.ErrNotImplemented
}

// RenameSecurityGroup implements rename-security-group operation.
//
// Changes the name only. Use the rule endpoints to change rules.
//
// PATCH /api/v1/security-groups/{securityGroupId}
func (UnimplementedHandler) RenameSecurityGroup(ctx context.Context, req *RenameSecurityGroupRequestBody, params RenameSecurityGroupParams) (r *SecurityGroupResource, _ error) {
	return r, ht.ErrNotImplemented
}

// SetFloatingIPBandwidth implements set-floating-ip-bandwidth operation.
//
// Creates a Billing order, including for metered pricing. The price must belong to the resource’s
// Billing Plan; applicable contract pricing is resolved by Billing. Technical capacity is checked
// before sellable quota is reserved. Provisioning continues automatically after payment; do not submit
// a new purchase after paying. Reuse the original idempotency key after an uncertain response.
//
// PUT /api/v1/floating-ips/{floatingIpId}/bandwidth
func (UnimplementedHandler) SetFloatingIPBandwidth(ctx context.Context, req *SetBandwidthRequestBody, params SetFloatingIPBandwidthParams) (r *PlacedOrder, _ error) {
	return r, ht.ErrNotImplemented
}

// SetResourceIdlePolicy implements set-resource-idle-policy operation.
//
// Requires permission to delete this resource. Enabling schedules reclamation only after the resource
// is continuously unreferenced for the requested retention. Existing claims, attachments and
// unfinished operations always prevent reclamation.
//
// PUT /api/v1/resources/{resourceType}/{resourceId}/idle-policy
func (UnimplementedHandler) SetResourceIdlePolicy(ctx context.Context, req *IdlePolicy, params SetResourceIdlePolicyParams) (r *ReclamationState, _ error) {
	return r, ht.ErrNotImplemented
}

// SuggestSubnetCidr implements suggest-subnet-cidr operation.
//
// The returned value is a suggestion and is validated again when the subnet is created. It exists to
// avoid errors when computing the next free CIDR by hand.
//
// GET /api/v1/private-networks/{privateNetworkId}/subnets/next-free-cidr
func (UnimplementedHandler) SuggestSubnetCidr(ctx context.Context, params SuggestSubnetCidrParams) (r *NextFreeCidrResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// UnbindFloatingIP implements unbind-floating-ip operation.
//
// The address remains held by the project and simply no longer points at any network interface.
//
// DELETE /api/v1/floating-ips/{floatingIpId}/binding
func (UnimplementedHandler) UnbindFloatingIP(ctx context.Context, params UnbindFloatingIPParams) (r *FloatingIPResource, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
