// Code generated by ogen, DO NOT EDIT.

package storagev1server

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/google/uuid"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/Attachment
type Attachment struct {
	ID         uuid.UUID         `json:"id"`
	UsageID    uuid.UUID         `json:"usage_id"`
	Resource   ResourceReference `json:"resource"`
	Consumer   ResourceReference `json:"consumer"`
	State      AttachmentState   `json:"state"`
	Generation int64             `json:"generation"`
	Device     OptString         `json:"device"`
	ReadOnly   bool              `json:"read_only"`
	CreatedAt  time.Time         `json:"created_at"`
	UpdatedAt  time.Time         `json:"updated_at"`
}

// GetID returns the value of ID.
func (s *Attachment) GetID() uuid.UUID {
	return s.ID
}

// GetUsageID returns the value of UsageID.
func (s *Attachment) GetUsageID() uuid.UUID {
	return s.UsageID
}

// GetResource returns the value of Resource.
func (s *Attachment) GetResource() ResourceReference {
	return s.Resource
}

// GetConsumer returns the value of Consumer.
func (s *Attachment) GetConsumer() ResourceReference {
	return s.Consumer
}

// GetState returns the value of State.
func (s *Attachment) GetState() AttachmentState {
	return s.State
}

// GetGeneration returns the value of Generation.
func (s *Attachment) GetGeneration() int64 {
	return s.Generation
}

// GetDevice returns the value of Device.
func (s *Attachment) GetDevice() OptString {
	return s.Device
}

// GetReadOnly returns the value of ReadOnly.
func (s *Attachment) GetReadOnly() bool {
	return s.ReadOnly
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Attachment) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Attachment) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Attachment) SetID(val uuid.UUID) {
	s.ID = val
}

// SetUsageID sets the value of UsageID.
func (s *Attachment) SetUsageID(val uuid.UUID) {
	s.UsageID = val
}

// SetResource sets the value of Resource.
func (s *Attachment) SetResource(val ResourceReference) {
	s.Resource = val
}

// SetConsumer sets the value of Consumer.
func (s *Attachment) SetConsumer(val ResourceReference) {
	s.Consumer = val
}

// SetState sets the value of State.
func (s *Attachment) SetState(val AttachmentState) {
	s.State = val
}

// SetGeneration sets the value of Generation.
func (s *Attachment) SetGeneration(val int64) {
	s.Generation = val
}

// SetDevice sets the value of Device.
func (s *Attachment) SetDevice(val OptString) {
	s.Device = val
}

// SetReadOnly sets the value of ReadOnly.
func (s *Attachment) SetReadOnly(val bool) {
	s.ReadOnly = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Attachment) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Attachment) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// Ref: #/components/schemas/AttachmentList
type AttachmentList struct {
	Items      []Attachment     `json:"items"`
	Pagination OffsetPagination `json:"pagination"`
}

// GetItems returns the value of Items.
func (s *AttachmentList) GetItems() []Attachment {
	return s.Items
}

// GetPagination returns the value of Pagination.
func (s *AttachmentList) GetPagination() OffsetPagination {
	return s.Pagination
}

// SetItems sets the value of Items.
func (s *AttachmentList) SetItems(val []Attachment) {
	s.Items = val
}

// SetPagination sets the value of Pagination.
func (s *AttachmentList) SetPagination(val OffsetPagination) {
	s.Pagination = val
}

type AttachmentState string

const (
	AttachmentStateReserved  AttachmentState = "reserved"
	AttachmentStateAttaching AttachmentState = "attaching"
	AttachmentStateAttached  AttachmentState = "attached"
	AttachmentStateDetaching AttachmentState = "detaching"
	AttachmentStateDetached  AttachmentState = "detached"
	AttachmentStateUnknown   AttachmentState = "unknown"
)

// AllValues returns all AttachmentState values.
func (AttachmentState) AllValues() []AttachmentState {
	return []AttachmentState{
		AttachmentStateReserved,
		AttachmentStateAttaching,
		AttachmentStateAttached,
		AttachmentStateDetaching,
		AttachmentStateDetached,
		AttachmentStateUnknown,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AttachmentState) MarshalText() ([]byte, error) {
	switch s {
	case AttachmentStateReserved:
		return []byte(s), nil
	case AttachmentStateAttaching:
		return []byte(s), nil
	case AttachmentStateAttached:
		return []byte(s), nil
	case AttachmentStateDetaching:
		return []byte(s), nil
	case AttachmentStateDetached:
		return []byte(s), nil
	case AttachmentStateUnknown:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AttachmentState) UnmarshalText(data []byte) error {
	switch AttachmentState(data) {
	case AttachmentStateReserved:
		*s = AttachmentStateReserved
		return nil
	case AttachmentStateAttaching:
		*s = AttachmentStateAttaching
		return nil
	case AttachmentStateAttached:
		*s = AttachmentStateAttached
		return nil
	case AttachmentStateDetaching:
		*s = AttachmentStateDetaching
		return nil
	case AttachmentStateDetached:
		*s = AttachmentStateDetached
		return nil
	case AttachmentStateUnknown:
		*s = AttachmentStateUnknown
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// Specify exactly one of id or lookup_key. A lookup key is scoped to the product of the resource
// service.
// Ref: #/components/schemas/CatalogReference
type CatalogReference struct {
	ID        OptUUID   `json:"id"`
	LookupKey OptString `json:"lookup_key"`
}

// GetID returns the value of ID.
func (s *CatalogReference) GetID() OptUUID {
	return s.ID
}

// GetLookupKey returns the value of LookupKey.
func (s *CatalogReference) GetLookupKey() OptString {
	return s.LookupKey
}

// SetID sets the value of ID.
func (s *CatalogReference) SetID(val OptUUID) {
	s.ID = val
}

// SetLookupKey sets the value of LookupKey.
func (s *CatalogReference) SetLookupKey(val OptString) {
	s.LookupKey = val
}

// Ref: #/components/schemas/CreateDiskRequest
type CreateDiskRequest struct {
	DiskTypeID uuid.UUID        `json:"disk_type_id"`
	Name       string           `json:"name"`
	SizeGB     int64            `json:"size_gb"`
	Price      CatalogReference `json:"price"`
	Order      OrderOptions     `json:"order"`
}

// GetDiskTypeID returns the value of DiskTypeID.
func (s *CreateDiskRequest) GetDiskTypeID() uuid.UUID {
	return s.DiskTypeID
}

// GetName returns the value of Name.
func (s *CreateDiskRequest) GetName() string {
	return s.Name
}

// GetSizeGB returns the value of SizeGB.
func (s *CreateDiskRequest) GetSizeGB() int64 {
	return s.SizeGB
}

// GetPrice returns the value of Price.
func (s *CreateDiskRequest) GetPrice() CatalogReference {
	return s.Price
}

// GetOrder returns the value of Order.
func (s *CreateDiskRequest) GetOrder() OrderOptions {
	return s.Order
}

// SetDiskTypeID sets the value of DiskTypeID.
func (s *CreateDiskRequest) SetDiskTypeID(val uuid.UUID) {
	s.DiskTypeID = val
}

// SetName sets the value of Name.
func (s *CreateDiskRequest) SetName(val string) {
	s.Name = val
}

// SetSizeGB sets the value of SizeGB.
func (s *CreateDiskRequest) SetSizeGB(val int64) {
	s.SizeGB = val
}

// SetPrice sets the value of Price.
func (s *CreateDiskRequest) SetPrice(val CatalogReference) {
	s.Price = val
}

// SetOrder sets the value of Order.
func (s *CreateDiskRequest) SetOrder(val OrderOptions) {
	s.Order = val
}

// DeleteDiskNoContent is response for DeleteDisk operation.
type DeleteDiskNoContent struct{}

// Ref: #/components/schemas/Disk
type Disk struct {
	ID                 uuid.UUID      `json:"id"`
	Name               string         `json:"name"`
	RegionID           uuid.UUID      `json:"region_id"`
	AvailabilityZoneID uuid.UUID      `json:"availability_zone_id"`
	DiskTypeID         uuid.UUID      `json:"disk_type_id"`
	SizeGB             int64          `json:"size_gb"`
	Status             DiskStatus     `json:"status"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	DeletedAt          OptNilDateTime `json:"deleted_at"`
}

// GetID returns the value of ID.
func (s *Disk) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *Disk) GetName() string {
	return s.Name
}

// GetRegionID returns the value of RegionID.
func (s *Disk) GetRegionID() uuid.UUID {
	return s.RegionID
}

// GetAvailabilityZoneID returns the value of AvailabilityZoneID.
func (s *Disk) GetAvailabilityZoneID() uuid.UUID {
	return s.AvailabilityZoneID
}

// GetDiskTypeID returns the value of DiskTypeID.
func (s *Disk) GetDiskTypeID() uuid.UUID {
	return s.DiskTypeID
}

// GetSizeGB returns the value of SizeGB.
func (s *Disk) GetSizeGB() int64 {
	return s.SizeGB
}

// GetStatus returns the value of Status.
func (s *Disk) GetStatus() DiskStatus {
	return s.Status
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Disk) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Disk) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// GetDeletedAt returns the value of DeletedAt.
func (s *Disk) GetDeletedAt() OptNilDateTime {
	return s.DeletedAt
}

// SetID sets the value of ID.
func (s *Disk) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Disk) SetName(val string) {
	s.Name = val
}

// SetRegionID sets the value of RegionID.
func (s *Disk) SetRegionID(val uuid.UUID) {
	s.RegionID = val
}

// SetAvailabilityZoneID sets the value of AvailabilityZoneID.
func (s *Disk) SetAvailabilityZoneID(val uuid.UUID) {
	s.AvailabilityZoneID = val
}

// SetDiskTypeID sets the value of DiskTypeID.
func (s *Disk) SetDiskTypeID(val uuid.UUID) {
	s.DiskTypeID = val
}

// SetSizeGB sets the value of SizeGB.
func (s *Disk) SetSizeGB(val int64) {
	s.SizeGB = val
}

// SetStatus sets the value of Status.
func (s *Disk) SetStatus(val DiskStatus) {
	s.Status = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Disk) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Disk) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// SetDeletedAt sets the value of DeletedAt.
func (s *Disk) SetDeletedAt(val OptNilDateTime) {
	s.DeletedAt = val
}

// Ref: #/components/schemas/DiskList
type DiskList struct {
	Items      []Disk           `json:"items"`
	Pagination OffsetPagination `json:"pagination"`
}

// GetItems returns the value of Items.
func (s *DiskList) GetItems() []Disk {
	return s.Items
}

// GetPagination returns the value of Pagination.
func (s *DiskList) GetPagination() OffsetPagination {
	return s.Pagination
}

// SetItems sets the value of Items.
func (s *DiskList) SetItems(val []Disk) {
	s.Items = val
}

// SetPagination sets the value of Pagination.
func (s *DiskList) SetPagination(val OffsetPagination) {
	s.Pagination = val
}

type DiskStatus string

const (
	DiskStatusProvisioning DiskStatus = "provisioning"
	DiskStatusAvailable    DiskStatus = "available"
	DiskStatusAttaching    DiskStatus = "attaching"
	DiskStatusInUse        DiskStatus = "in_use"
	DiskStatusDetaching    DiskStatus = "detaching"
	DiskStatusResizing     DiskStatus = "resizing"
	DiskStatusReverting    DiskStatus = "reverting"
	DiskStatusRestoring    DiskStatus = "restoring"
	DiskStatusReleasing    DiskStatus = "releasing"
	DiskStatusDeleting     DiskStatus = "deleting"
	DiskStatusError        DiskStatus = "error"
)

// AllValues returns all DiskStatus values.
func (DiskStatus) AllValues() []DiskStatus {
	return []DiskStatus{
		DiskStatusProvisioning,
		DiskStatusAvailable,
		DiskStatusAttaching,
		DiskStatusInUse,
		DiskStatusDetaching,
		DiskStatusResizing,
		DiskStatusReverting,
		DiskStatusRestoring,
		DiskStatusReleasing,
		DiskStatusDeleting,
		DiskStatusError,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s DiskStatus) MarshalText() ([]byte, error) {
	switch s {
	case DiskStatusProvisioning:
		return []byte(s), nil
	case DiskStatusAvailable:
		return []byte(s), nil
	case DiskStatusAttaching:
		return []byte(s), nil
	case DiskStatusInUse:
		return []byte(s), nil
	case DiskStatusDetaching:
		return []byte(s), nil
	case DiskStatusResizing:
		return []byte(s), nil
	case DiskStatusReverting:
		return []byte(s), nil
	case DiskStatusRestoring:
		return []byte(s), nil
	case DiskStatusReleasing:
		return []byte(s), nil
	case DiskStatusDeleting:
		return []byte(s), nil
	case DiskStatusError:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *DiskStatus) UnmarshalText(data []byte) error {
	switch DiskStatus(data) {
	case DiskStatusProvisioning:
		*s = DiskStatusProvisioning
		return nil
	case DiskStatusAvailable:
		*s = DiskStatusAvailable
		return nil
	case DiskStatusAttaching:
		*s = DiskStatusAttaching
		return nil
	case DiskStatusInUse:
		*s = DiskStatusInUse
		return nil
	case DiskStatusDetaching:
		*s = DiskStatusDetaching
		return nil
	case DiskStatusResizing:
		*s = DiskStatusResizing
		return nil
	case DiskStatusReverting:
		*s = DiskStatusReverting
		return nil
	case DiskStatusRestoring:
		*s = DiskStatusRestoring
		return nil
	case DiskStatusReleasing:
		*s = DiskStatusReleasing
		return nil
	case DiskStatusDeleting:
		*s = DiskStatusDeleting
		return nil
	case DiskStatusError:
		*s = DiskStatusError
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/DiskType
type DiskType struct {
	ID                 uuid.UUID     `json:"id"`
	LookupKey          string        `json:"lookup_key"`
	Name               string        `json:"name"`
	Media              DiskTypeMedia `json:"media"`
	RegionID           uuid.UUID     `json:"region_id"`
	AvailabilityZoneID uuid.UUID     `json:"availability_zone_id"`
	MinSizeGB          int64         `json:"min_size_gb"`
	MaxSizeGB          int64         `json:"max_size_gb"`
	StepGB             int64         `json:"step_gb"`
	ForSystem          bool          `json:"for_system"`
	BillingPlanID      uuid.UUID     `json:"billing_plan_id"`
}

// GetID returns the value of ID.
func (s *DiskType) GetID() uuid.UUID {
	return s.ID
}

// GetLookupKey returns the value of LookupKey.
func (s *DiskType) GetLookupKey() string {
	return s.LookupKey
}

// GetName returns the value of Name.
func (s *DiskType) GetName() string {
	return s.Name
}

// GetMedia returns the value of Media.
func (s *DiskType) GetMedia() DiskTypeMedia {
	return s.Media
}

// GetRegionID returns the value of RegionID.
func (s *DiskType) GetRegionID() uuid.UUID {
	return s.RegionID
}

// GetAvailabilityZoneID returns the value of AvailabilityZoneID.
func (s *DiskType) GetAvailabilityZoneID() uuid.UUID {
	return s.AvailabilityZoneID
}

// GetMinSizeGB returns the value of MinSizeGB.
func (s *DiskType) GetMinSizeGB() int64 {
	return s.MinSizeGB
}

// GetMaxSizeGB returns the value of MaxSizeGB.
func (s *DiskType) GetMaxSizeGB() int64 {
	return s.MaxSizeGB
}

// GetStepGB returns the value of StepGB.
func (s *DiskType) GetStepGB() int64 {
	return s.StepGB
}

// GetForSystem returns the value of ForSystem.
func (s *DiskType) GetForSystem() bool {
	return s.ForSystem
}

// GetBillingPlanID returns the value of BillingPlanID.
func (s *DiskType) GetBillingPlanID() uuid.UUID {
	return s.BillingPlanID
}

// SetID sets the value of ID.
func (s *DiskType) SetID(val uuid.UUID) {
	s.ID = val
}

// SetLookupKey sets the value of LookupKey.
func (s *DiskType) SetLookupKey(val string) {
	s.LookupKey = val
}

// SetName sets the value of Name.
func (s *DiskType) SetName(val string) {
	s.Name = val
}

// SetMedia sets the value of Media.
func (s *DiskType) SetMedia(val DiskTypeMedia) {
	s.Media = val
}

// SetRegionID sets the value of RegionID.
func (s *DiskType) SetRegionID(val uuid.UUID) {
	s.RegionID = val
}

// SetAvailabilityZoneID sets the value of AvailabilityZoneID.
func (s *DiskType) SetAvailabilityZoneID(val uuid.UUID) {
	s.AvailabilityZoneID = val
}

// SetMinSizeGB sets the value of MinSizeGB.
func (s *DiskType) SetMinSizeGB(val int64) {
	s.MinSizeGB = val
}

// SetMaxSizeGB sets the value of MaxSizeGB.
func (s *DiskType) SetMaxSizeGB(val int64) {
	s.MaxSizeGB = val
}

// SetStepGB sets the value of StepGB.
func (s *DiskType) SetStepGB(val int64) {
	s.StepGB = val
}

// SetForSystem sets the value of ForSystem.
func (s *DiskType) SetForSystem(val bool) {
	s.ForSystem = val
}

// SetBillingPlanID sets the value of BillingPlanID.
func (s *DiskType) SetBillingPlanID(val uuid.UUID) {
	s.BillingPlanID = val
}

// Ref: #/components/schemas/DiskTypeList
type DiskTypeList struct {
	Items      []DiskType       `json:"items"`
	Pagination OffsetPagination `json:"pagination"`
}

// GetItems returns the value of Items.
func (s *DiskTypeList) GetItems() []DiskType {
	return s.Items
}

// GetPagination returns the value of Pagination.
func (s *DiskTypeList) GetPagination() OffsetPagination {
	return s.Pagination
}

// SetItems sets the value of Items.
func (s *DiskTypeList) SetItems(val []DiskType) {
	s.Items = val
}

// SetPagination sets the value of Pagination.
func (s *DiskTypeList) SetPagination(val OffsetPagination) {
	s.Pagination = val
}

type DiskTypeMedia string

const (
	DiskTypeMediaSsd  DiskTypeMedia = "ssd"
	DiskTypeMediaHdd  DiskTypeMedia = "hdd"
	DiskTypeMediaNvme DiskTypeMedia = "nvme"
)

// AllValues returns all DiskTypeMedia values.
func (DiskTypeMedia) AllValues() []DiskTypeMedia {
	return []DiskTypeMedia{
		DiskTypeMediaSsd,
		DiskTypeMediaHdd,
		DiskTypeMediaNvme,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s DiskTypeMedia) MarshalText() ([]byte, error) {
	switch s {
	case DiskTypeMediaSsd:
		return []byte(s), nil
	case DiskTypeMediaHdd:
		return []byte(s), nil
	case DiskTypeMediaNvme:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *DiskTypeMedia) UnmarshalText(data []byte) error {
	switch DiskTypeMedia(data) {
	case DiskTypeMediaSsd:
		*s = DiskTypeMediaSsd
		return nil
	case DiskTypeMediaHdd:
		*s = DiskTypeMediaHdd
		return nil
	case DiskTypeMediaNvme:
		*s = DiskTypeMediaNvme
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Error
type Error struct {
	Code    OptString `json:"code"`
	Message string    `json:"message"`
	// What a given `code` carries alongside the message. The keys depend on the code, and a client that
	// does not recognise one ignores it.
	Meta   OptErrorMeta `json:"meta"`
	Status int64        `json:"status"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() OptString {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// GetMeta returns the value of Meta.
func (s *Error) GetMeta() OptErrorMeta {
	return s.Meta
}

// GetStatus returns the value of Status.
func (s *Error) GetStatus() int64 {
	return s.Status
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val OptString) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// SetMeta sets the value of Meta.
func (s *Error) SetMeta(val OptErrorMeta) {
	s.Meta = val
}

// SetStatus sets the value of Status.
func (s *Error) SetStatus(val int64) {
	s.Status = val
}

// What a given `code` carries alongside the message. The keys depend on the code, and a client that
// does not recognise one ignores it.
type ErrorMeta map[string]jx.Raw

func (s *ErrorMeta) init() ErrorMeta {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// Automatic reclamation is disabled by default. When enabled, retention starts after the last live
// claim is confirmed released. Traffic, IO and consumer heartbeats do not affect eligibility.
// Ref: #/components/schemas/IdlePolicy
type IdlePolicy struct {
	Enabled          bool  `json:"enabled"`
	RetentionSeconds int64 `json:"retention_seconds"`
}

// GetEnabled returns the value of Enabled.
func (s *IdlePolicy) GetEnabled() bool {
	return s.Enabled
}

// GetRetentionSeconds returns the value of RetentionSeconds.
func (s *IdlePolicy) GetRetentionSeconds() int64 {
	return s.RetentionSeconds
}

// SetEnabled sets the value of Enabled.
func (s *IdlePolicy) SetEnabled(val bool) {
	s.Enabled = val
}

// SetRetentionSeconds sets the value of RetentionSeconds.
func (s *IdlePolicy) SetRetentionSeconds(val int64) {
	s.RetentionSeconds = val
}

// Pagination metadata for stable numbered pages. total_count is returned only when the operation can
// determine it without an unbounded scan.
// Ref: #/components/schemas/OffsetPagination
type OffsetPagination struct {
	Page       int64    `json:"page"`
	PageSize   int64    `json:"page_size"`
	TotalCount OptInt64 `json:"total_count"`
}

// GetPage returns the value of Page.
func (s *OffsetPagination) GetPage() int64 {
	return s.Page
}

// GetPageSize returns the value of PageSize.
func (s *OffsetPagination) GetPageSize() int64 {
	return s.PageSize
}

// GetTotalCount returns the value of TotalCount.
func (s *OffsetPagination) GetTotalCount() OptInt64 {
	return s.TotalCount
}

// SetPage sets the value of Page.
func (s *OffsetPagination) SetPage(val int64) {
	s.Page = val
}

// SetPageSize sets the value of PageSize.
func (s *OffsetPagination) SetPageSize(val int64) {
	s.PageSize = val
}

// SetTotalCount sets the value of TotalCount.
func (s *OffsetPagination) SetTotalCount(val OptInt64) {
	s.TotalCount = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptErrorMeta returns new OptErrorMeta with value set to v.
func NewOptErrorMeta(v ErrorMeta) OptErrorMeta {
	return OptErrorMeta{
		Value: v,
		Set:   true,
	}
}

// OptErrorMeta is optional ErrorMeta.
type OptErrorMeta struct {
	Value ErrorMeta
	Set   bool
}

// IsSet returns true if OptErrorMeta was set.
func (o OptErrorMeta) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptErrorMeta) Reset() {
	var v ErrorMeta
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptErrorMeta) SetTo(v ErrorMeta) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptErrorMeta) Get() (v ErrorMeta, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptErrorMeta) Or(d ErrorMeta) ErrorMeta {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilDateTime returns new OptNilDateTime with value set to v.
func NewOptNilDateTime(v time.Time) OptNilDateTime {
	return OptNilDateTime{
		Value: v,
		Set:   true,
	}
}

// OptNilDateTime is optional nullable time.Time.
type OptNilDateTime struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDateTime was set.
func (o OptNilDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDateTime) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilDateTime) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentPlan returns new OptPaymentPlan with value set to v.
func NewOptPaymentPlan(v PaymentPlan) OptPaymentPlan {
	return OptPaymentPlan{
		Value: v,
		Set:   true,
	}
}

// OptPaymentPlan is optional PaymentPlan.
type OptPaymentPlan struct {
	Value PaymentPlan
	Set   bool
}

// IsSet returns true if OptPaymentPlan was set.
func (o OptPaymentPlan) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentPlan) Reset() {
	var v PaymentPlan
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentPlan) SetTo(v PaymentPlan) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentPlan) Get() (v PaymentPlan, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentPlan) Or(d PaymentPlan) PaymentPlan {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Reuse the same key for retries of the same purchase. Reusing it with a different request fails.
// Billing selects contract pricing, applies eligible grants and promotions, and owns payment
// challenges and expiry.
// Ref: #/components/schemas/OrderOptions
type OrderOptions struct {
	IdempotencyKey string         `json:"idempotency_key"`
	PaymentPlan    OptPaymentPlan `json:"payment_plan"`
	ExpectedAmount OptString      `json:"expected_amount"`
	RedemptionCode OptString      `json:"redemption_code"`
}

// GetIdempotencyKey returns the value of IdempotencyKey.
func (s *OrderOptions) GetIdempotencyKey() string {
	return s.IdempotencyKey
}

// GetPaymentPlan returns the value of PaymentPlan.
func (s *OrderOptions) GetPaymentPlan() OptPaymentPlan {
	return s.PaymentPlan
}

// GetExpectedAmount returns the value of ExpectedAmount.
func (s *OrderOptions) GetExpectedAmount() OptString {
	return s.ExpectedAmount
}

// GetRedemptionCode returns the value of RedemptionCode.
func (s *OrderOptions) GetRedemptionCode() OptString {
	return s.RedemptionCode
}

// SetIdempotencyKey sets the value of IdempotencyKey.
func (s *OrderOptions) SetIdempotencyKey(val string) {
	s.IdempotencyKey = val
}

// SetPaymentPlan sets the value of PaymentPlan.
func (s *OrderOptions) SetPaymentPlan(val OptPaymentPlan) {
	s.PaymentPlan = val
}

// SetExpectedAmount sets the value of ExpectedAmount.
func (s *OrderOptions) SetExpectedAmount(val OptString) {
	s.ExpectedAmount = val
}

// SetRedemptionCode sets the value of RedemptionCode.
func (s *OrderOptions) SetRedemptionCode(val OptString) {
	s.RedemptionCode = val
}

// Requested funding split. This does not select a card or payment provider; complete payment through
// Billing.
// Ref: #/components/schemas/PaymentPlan
type PaymentPlan struct {
	BalanceAmount  string `json:"balance_amount"`
	ProviderAmount string `json:"provider_amount"`
}

// GetBalanceAmount returns the value of BalanceAmount.
func (s *PaymentPlan) GetBalanceAmount() string {
	return s.BalanceAmount
}

// GetProviderAmount returns the value of ProviderAmount.
func (s *PaymentPlan) GetProviderAmount() string {
	return s.ProviderAmount
}

// SetBalanceAmount sets the value of BalanceAmount.
func (s *PaymentPlan) SetBalanceAmount(val string) {
	s.BalanceAmount = val
}

// SetProviderAmount sets the value of ProviderAmount.
func (s *PaymentPlan) SetProviderAmount(val string) {
	s.ProviderAmount = val
}

// A billable order has been created. Read it from the billing API to find out what is owed and whether
// payment is still required.
//
// Only the identifier is returned. Amounts and state are not repeated here; the order itself is the
// single source for them.
// Ref: #/components/schemas/PlacedOrder
type PlacedOrder struct {
	// Identifies the order. Use it to read the order and, where payment is required, to pay it.
	//
	// An order is created even when nothing is owed, such as a plan with no charge or one covered entirely
	// by granted credit. Such an order is already settled, and no payment step applies.
	OrderID uuid.UUID `json:"order_id"`
}

// GetOrderID returns the value of OrderID.
func (s *PlacedOrder) GetOrderID() uuid.UUID {
	return s.OrderID
}

// SetOrderID sets the value of OrderID.
func (s *PlacedOrder) SetOrderID(val uuid.UUID) {
	s.OrderID = val
}

// Ref: #/components/schemas/ReclamationState
type ReclamationState struct {
	Resource         ResourceReference      `json:"resource"`
	Policy           IdlePolicy             `json:"policy"`
	ActiveUsageCount int64                  `json:"active_usage_count"`
	UnreferencedAt   OptDateTime            `json:"unreferenced_at"`
	EligibleAt       OptDateTime            `json:"eligible_at"`
	Status           ReclamationStateStatus `json:"status"`
	BlockedReasons   []string               `json:"blocked_reasons"`
}

// GetResource returns the value of Resource.
func (s *ReclamationState) GetResource() ResourceReference {
	return s.Resource
}

// GetPolicy returns the value of Policy.
func (s *ReclamationState) GetPolicy() IdlePolicy {
	return s.Policy
}

// GetActiveUsageCount returns the value of ActiveUsageCount.
func (s *ReclamationState) GetActiveUsageCount() int64 {
	return s.ActiveUsageCount
}

// GetUnreferencedAt returns the value of UnreferencedAt.
func (s *ReclamationState) GetUnreferencedAt() OptDateTime {
	return s.UnreferencedAt
}

// GetEligibleAt returns the value of EligibleAt.
func (s *ReclamationState) GetEligibleAt() OptDateTime {
	return s.EligibleAt
}

// GetStatus returns the value of Status.
func (s *ReclamationState) GetStatus() ReclamationStateStatus {
	return s.Status
}

// GetBlockedReasons returns the value of BlockedReasons.
func (s *ReclamationState) GetBlockedReasons() []string {
	return s.BlockedReasons
}

// SetResource sets the value of Resource.
func (s *ReclamationState) SetResource(val ResourceReference) {
	s.Resource = val
}

// SetPolicy sets the value of Policy.
func (s *ReclamationState) SetPolicy(val IdlePolicy) {
	s.Policy = val
}

// SetActiveUsageCount sets the value of ActiveUsageCount.
func (s *ReclamationState) SetActiveUsageCount(val int64) {
	s.ActiveUsageCount = val
}

// SetUnreferencedAt sets the value of UnreferencedAt.
func (s *ReclamationState) SetUnreferencedAt(val OptDateTime) {
	s.UnreferencedAt = val
}

// SetEligibleAt sets the value of EligibleAt.
func (s *ReclamationState) SetEligibleAt(val OptDateTime) {
	s.EligibleAt = val
}

// SetStatus sets the value of Status.
func (s *ReclamationState) SetStatus(val ReclamationStateStatus) {
	s.Status = val
}

// SetBlockedReasons sets the value of BlockedReasons.
func (s *ReclamationState) SetBlockedReasons(val []string) {
	s.BlockedReasons = val
}

type ReclamationStateStatus string

const (
	ReclamationStateStatusRetained   ReclamationStateStatus = "retained"
	ReclamationStateStatusInUse      ReclamationStateStatus = "in_use"
	ReclamationStateStatusIdle       ReclamationStateStatus = "idle"
	ReclamationStateStatusReclaiming ReclamationStateStatus = "reclaiming"
	ReclamationStateStatusDeleted    ReclamationStateStatus = "deleted"
)

// AllValues returns all ReclamationStateStatus values.
func (ReclamationStateStatus) AllValues() []ReclamationStateStatus {
	return []ReclamationStateStatus{
		ReclamationStateStatusRetained,
		ReclamationStateStatusInUse,
		ReclamationStateStatusIdle,
		ReclamationStateStatusReclaiming,
		ReclamationStateStatusDeleted,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ReclamationStateStatus) MarshalText() ([]byte, error) {
	switch s {
	case ReclamationStateStatusRetained:
		return []byte(s), nil
	case ReclamationStateStatusInUse:
		return []byte(s), nil
	case ReclamationStateStatusIdle:
		return []byte(s), nil
	case ReclamationStateStatusReclaiming:
		return []byte(s), nil
	case ReclamationStateStatusDeleted:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ReclamationStateStatus) UnmarshalText(data []byte) error {
	switch ReclamationStateStatus(data) {
	case ReclamationStateStatusRetained:
		*s = ReclamationStateStatusRetained
		return nil
	case ReclamationStateStatusInUse:
		*s = ReclamationStateStatusInUse
		return nil
	case ReclamationStateStatusIdle:
		*s = ReclamationStateStatusIdle
		return nil
	case ReclamationStateStatusReclaiming:
		*s = ReclamationStateStatusReclaiming
		return nil
	case ReclamationStateStatusDeleted:
		*s = ReclamationStateStatusDeleted
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/RenameRequest
type RenameRequest struct {
	Name string `json:"name"`
}

// GetName returns the value of Name.
func (s *RenameRequest) GetName() string {
	return s.Name
}

// SetName sets the value of Name.
func (s *RenameRequest) SetName(val string) {
	s.Name = val
}

// A resource identified within its owning service. The project is taken from the containing usage or
// request.
// Ref: #/components/schemas/ResourceReference
type ResourceReference struct {
	Service string    `json:"service"`
	Type    string    `json:"type"`
	ID      uuid.UUID `json:"id"`
}

// GetService returns the value of Service.
func (s *ResourceReference) GetService() string {
	return s.Service
}

// GetType returns the value of Type.
func (s *ResourceReference) GetType() string {
	return s.Type
}

// GetID returns the value of ID.
func (s *ResourceReference) GetID() uuid.UUID {
	return s.ID
}

// SetService sets the value of Service.
func (s *ResourceReference) SetService(val string) {
	s.Service = val
}

// SetType sets the value of Type.
func (s *ResourceReference) SetType(val string) {
	s.Type = val
}

// SetID sets the value of ID.
func (s *ResourceReference) SetID(val uuid.UUID) {
	s.ID = val
}

type ResourceType string

const (
	ResourceTypeDisk ResourceType = "disk"
)

// AllValues returns all ResourceType values.
func (ResourceType) AllValues() []ResourceType {
	return []ResourceType{
		ResourceTypeDisk,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ResourceType) MarshalText() ([]byte, error) {
	switch s {
	case ResourceTypeDisk:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ResourceType) UnmarshalText(data []byte) error {
	switch ResourceType(data) {
	case ResourceTypeDisk:
		*s = ResourceTypeDisk
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ResourceTypePath string

const (
	ResourceTypePathDisk ResourceTypePath = "disk"
)

// AllValues returns all ResourceTypePath values.
func (ResourceTypePath) AllValues() []ResourceTypePath {
	return []ResourceTypePath{
		ResourceTypePathDisk,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ResourceTypePath) MarshalText() ([]byte, error) {
	switch s {
	case ResourceTypePathDisk:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ResourceTypePath) UnmarshalText(data []byte) error {
	switch ResourceTypePath(data) {
	case ResourceTypePathDisk:
		*s = ResourceTypePathDisk
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// An authoritative claim held by the resource owner. Reserved, active and releasing claims all prevent
// idle reclamation. Stopped consumers retain their claims. Released claims remain readable.
// Ref: #/components/schemas/ResourceUsage
type ResourceUsage struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Resource    ResourceReference  `json:"resource"`
	Consumer    ResourceReference  `json:"consumer"`
	Purpose     string             `json:"purpose"`
	State       ResourceUsageState `json:"state"`
	Generation  int64              `json:"generation"`
	OperationID string             `json:"operation_id"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	ReleasedAt  OptDateTime        `json:"released_at"`
}

// GetID returns the value of ID.
func (s *ResourceUsage) GetID() uuid.UUID {
	return s.ID
}

// GetProjectID returns the value of ProjectID.
func (s *ResourceUsage) GetProjectID() uuid.UUID {
	return s.ProjectID
}

// GetResource returns the value of Resource.
func (s *ResourceUsage) GetResource() ResourceReference {
	return s.Resource
}

// GetConsumer returns the value of Consumer.
func (s *ResourceUsage) GetConsumer() ResourceReference {
	return s.Consumer
}

// GetPurpose returns the value of Purpose.
func (s *ResourceUsage) GetPurpose() string {
	return s.Purpose
}

// GetState returns the value of State.
func (s *ResourceUsage) GetState() ResourceUsageState {
	return s.State
}

// GetGeneration returns the value of Generation.
func (s *ResourceUsage) GetGeneration() int64 {
	return s.Generation
}

// GetOperationID returns the value of OperationID.
func (s *ResourceUsage) GetOperationID() string {
	return s.OperationID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *ResourceUsage) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *ResourceUsage) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// GetReleasedAt returns the value of ReleasedAt.
func (s *ResourceUsage) GetReleasedAt() OptDateTime {
	return s.ReleasedAt
}

// SetID sets the value of ID.
func (s *ResourceUsage) SetID(val uuid.UUID) {
	s.ID = val
}

// SetProjectID sets the value of ProjectID.
func (s *ResourceUsage) SetProjectID(val uuid.UUID) {
	s.ProjectID = val
}

// SetResource sets the value of Resource.
func (s *ResourceUsage) SetResource(val ResourceReference) {
	s.Resource = val
}

// SetConsumer sets the value of Consumer.
func (s *ResourceUsage) SetConsumer(val ResourceReference) {
	s.Consumer = val
}

// SetPurpose sets the value of Purpose.
func (s *ResourceUsage) SetPurpose(val string) {
	s.Purpose = val
}

// SetState sets the value of State.
func (s *ResourceUsage) SetState(val ResourceUsageState) {
	s.State = val
}

// SetGeneration sets the value of Generation.
func (s *ResourceUsage) SetGeneration(val int64) {
	s.Generation = val
}

// SetOperationID sets the value of OperationID.
func (s *ResourceUsage) SetOperationID(val string) {
	s.OperationID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *ResourceUsage) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *ResourceUsage) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// SetReleasedAt sets the value of ReleasedAt.
func (s *ResourceUsage) SetReleasedAt(val OptDateTime) {
	s.ReleasedAt = val
}

// Ref: #/components/schemas/ResourceUsageList
type ResourceUsageList struct {
	Items      []ResourceUsage  `json:"items"`
	Pagination OffsetPagination `json:"pagination"`
}

// GetItems returns the value of Items.
func (s *ResourceUsageList) GetItems() []ResourceUsage {
	return s.Items
}

// GetPagination returns the value of Pagination.
func (s *ResourceUsageList) GetPagination() OffsetPagination {
	return s.Pagination
}

// SetItems sets the value of Items.
func (s *ResourceUsageList) SetItems(val []ResourceUsage) {
	s.Items = val
}

// SetPagination sets the value of Pagination.
func (s *ResourceUsageList) SetPagination(val OffsetPagination) {
	s.Pagination = val
}

type ResourceUsageState string

const (
	ResourceUsageStateReserved  ResourceUsageState = "reserved"
	ResourceUsageStateActive    ResourceUsageState = "active"
	ResourceUsageStateReleasing ResourceUsageState = "releasing"
	ResourceUsageStateReleased  ResourceUsageState = "released"
)

// AllValues returns all ResourceUsageState values.
func (ResourceUsageState) AllValues() []ResourceUsageState {
	return []ResourceUsageState{
		ResourceUsageStateReserved,
		ResourceUsageStateActive,
		ResourceUsageStateReleasing,
		ResourceUsageStateReleased,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ResourceUsageState) MarshalText() ([]byte, error) {
	switch s {
	case ResourceUsageStateReserved:
		return []byte(s), nil
	case ResourceUsageStateActive:
		return []byte(s), nil
	case ResourceUsageStateReleasing:
		return []byte(s), nil
	case ResourceUsageStateReleased:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ResourceUsageState) UnmarshalText(data []byte) error {
	switch ResourceUsageState(data) {
	case ResourceUsageStateReserved:
		*s = ResourceUsageStateReserved
		return nil
	case ResourceUsageStateActive:
		*s = ResourceUsageStateActive
		return nil
	case ResourceUsageStateReleasing:
		*s = ResourceUsageStateReleasing
		return nil
	case ResourceUsageStateReleased:
		*s = ResourceUsageStateReleased
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
