// Code generated by ogen, DO NOT EDIT.

package tunnelv1server

// OperationName is the ogen operation name
type OperationName = string

const (
	ActOnTunnelOperation              OperationName = "ActOnTunnel"
	ChangeTunnelPlanOperation         OperationName = "ChangeTunnelPlan"
	CloseTunnelOperation              OperationName = "CloseTunnel"
	GetTunnelOperation                OperationName = "GetTunnel"
	GetTunnelSubscriptionOperation    OperationName = "GetTunnelSubscription"
	GetTunnelUsageOperation           OperationName = "GetTunnelUsage"
	ListTunnelOperationLogsOperation  OperationName = "ListTunnelOperationLogs"
	ListTunnelPlansOperation          OperationName = "ListTunnelPlans"
	ListTunnelUsageSeriesOperation    OperationName = "ListTunnelUsageSeries"
	OpenTunnelOperation               OperationName = "OpenTunnel"
	RotateTunnelSubscriptionOperation OperationName = "RotateTunnelSubscription"
	UpdateTunnelProfileOperation      OperationName = "UpdateTunnelProfile"
)
