// Code generated by ogen, DO NOT EDIT.

package dnsv1server

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/validate"
)

func (s *AliDNSConfig) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     256,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.AccessKeyID)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "access_key_id",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     256,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.AccessKeySecret)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "access_key_secret",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.RegionID.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     64,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "region_id",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *AppendRecordsRequestBody) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     253,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Name)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "name",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.TTL.Get(); ok {
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           0,
					MaxSet:        true,
					Max:           604800,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(value)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "ttl",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if err := func() error {
		if s.Values == nil {
			return errors.New("nil is invalid value")
		}
		if err := (validate.Array{
			MinLength:    1,
			MinLengthSet: true,
			MaxLength:    100,
			MaxLengthSet: true,
		}).ValidateLength(len(s.Values)); err != nil {
			return errors.Wrap(err, "array")
		}
		var failures []validate.FieldError
		for i, elem := range s.Values {
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     4096,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(elem)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "values",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *CloudflareConfig) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     512,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.APIToken)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "api_token",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ZoneToken.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     512,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "zone_token",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *CreateCredentialRequestBody) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Alidns.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "alidns",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Cloudflare.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "cloudflare",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     128,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Name)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "name",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.Provider.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "provider",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Route53.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "route53",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Tencentcloud.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "tencentcloud",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *CredentialResource) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Provider.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "provider",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.Status.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "status",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s CredentialStatus) Validate() error {
	switch s {
	case "active":
		return nil
	case "disabled":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *LengthAwarePageCredentialResource) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Items == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.Items {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "items",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *LengthAwarePageRecordSetResource) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Items == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.Items {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "items",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s Provider) Validate() error {
	switch s {
	case "cloudflare":
		return nil
	case "tencentcloud":
		return nil
	case "alidns":
		return nil
	case "route53":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *RecordSetResource) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if err := func() error {
		if s.Values == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "values",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s RecordType) Validate() error {
	switch s {
	case "A":
		return nil
	case "AAAA":
		return nil
	case "CNAME":
		return nil
	case "TXT":
		return nil
	case "MX":
		return nil
	case "NS":
		return nil
	case "SRV":
		return nil
	case "CAA":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *RenameCredentialRequestBody) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     128,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Name)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "name",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *Route53Config) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     256,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.AccessKeyID)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "access_key_id",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Region.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     64,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "region",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     256,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.SecretAccessKey)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "secret_access_key",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.SessionToken.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     2048,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "session_token",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *SetRecordSetRequestBody) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.TTL.Get(); ok {
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           0,
					MaxSet:        true,
					Max:           604800,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(value)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "ttl",
			Error: err,
		})
	}
	if err := func() error {
		if s.Values == nil {
			return errors.New("nil is invalid value")
		}
		if err := (validate.Array{
			MinLength:    1,
			MinLengthSet: true,
			MaxLength:    100,
			MaxLengthSet: true,
		}).ValidateLength(len(s.Values)); err != nil {
			return errors.Wrap(err, "array")
		}
		var failures []validate.FieldError
		for i, elem := range s.Values {
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     4096,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(elem)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "values",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *TencentCloudConfig) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     256,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.SecretID)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "secret_id",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     256,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.SecretKey)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "secret_key",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ZoneListResponseBody) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Items == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.Items {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "items",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ZoneResource) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Provider.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "provider",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}
