// Code generated by ogen, DO NOT EDIT.

package computev1server

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ActOnInstance implements act-on-instance operation.
//
// 重启默认为软重启，由操作系统正常关闭后重新启动。
//
// 系统已无响应时软重启不会生效，此时可设置 `force`
// 强制重启。强制重启不等待操作系统关闭，未落盘的数据会丢失。`force`
// 仅适用于 reboot。
//
// 已被平台停服的云服务器需先解除停服。
//
// 本接口立即返回，返回的 `status` 是变更中的瞬态：start 为 `starting`、stop 为
// `stopping`、reboot 为 `rebooting`。轮询云服务器详情直至落定为 `running` 或
// `stopped`。.
//
// POST /api/v1/instances/{instanceId}/actions
func (UnimplementedHandler) ActOnInstance(ctx context.Context, req *ActOnInstanceRequestBody, params ActOnInstanceParams) (r *InstanceResource, _ error) {
	return r, ht.ErrNotImplemented
}

// AllocateFloatingIP implements allocate-floating-ip operation.
//
// 若该私有网络尚未连通外网，会一并为其接入外网。
//
// IPv6 不通过本接口申请。IPv6
// 地址由私有网络自动下发至云服务器，在私有网络上启用即可。.
//
// POST /api/v1/floating-ips
func (UnimplementedHandler) AllocateFloatingIP(ctx context.Context, req *AllocateFloatingIPRequestBody) (r *FloatingIPResource, _ error) {
	return r, ht.ErrNotImplemented
}

// AttachDisk implements attach-disk operation.
//
// 云硬盘必须与云服务器位于同一地区和可用区。挂载后需在云服务器内自行分区并挂载文件系统。.
//
// POST /api/v1/instances/{instanceId}/disks
func (UnimplementedHandler) AttachDisk(ctx context.Context, req *AttachDiskRequestBody, params AttachDiskParams) (r *DiskResource, _ error) {
	return r, ht.ErrNotImplemented
}

// AttachInstanceFloatingIP implements attach-instance-floating-ip operation.
//
// 公网 IP 绑定在云服务器的主网卡上。.
//
// POST /api/v1/instances/{instanceId}/floating-ips
func (UnimplementedHandler) AttachInstanceFloatingIP(ctx context.Context, req *AttachFloatingIPRequestBody, params AttachInstanceFloatingIPParams) (r *FloatingIPResource, _ error) {
	return r, ht.ErrNotImplemented
}

// AttachPort implements attach-port operation.
//
// 挂载网卡.
//
// POST /api/v1/instances/{instanceId}/ports
func (UnimplementedHandler) AttachPort(ctx context.Context, req *AttachPortRequestBody, params AttachPortParams) (r *PortResource, _ error) {
	return r, ht.ErrNotImplemented
}

// BindFloatingIP implements bind-floating-ip operation.
//
// 将公网 IP 绑定到网卡.
//
// PUT /api/v1/floating-ips/{floatingIpId}/binding
func (UnimplementedHandler) BindFloatingIP(ctx context.Context, req *BindFloatingIPRequestBody, params BindFloatingIPParams) (r *FloatingIPResource, _ error) {
	return r, ht.ErrNotImplemented
}

// ConfirmInstanceResize implements confirm-instance-resize operation.
//
// 释放原规格占用的资源，`pending_instance_type_id`
// 成为生效机型并从此按它计费。.
//
// POST /api/v1/instances/{instanceId}/resize/confirm
func (UnimplementedHandler) ConfirmInstanceResize(ctx context.Context, params ConfirmInstanceResizeParams) (r *InstanceResource, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateBackup implements create-backup operation.
//
// 备份是云硬盘在独立存储中的一份完整副本：**源云硬盘删除后仍可恢复，且可恢复到本地区的其他可用区。**快照不具备这两项能力，它与源云硬盘位于同一存储，且源云硬盘存在快照时无法删除。
//
// 运行中云服务器上挂载的云硬盘、以及系统盘，均可创建备份。
//
// 备份耗时取决于数据量。接口返回时尚未完成，请轮询查看接口。.
//
// POST /api/v1/backups
func (UnimplementedHandler) CreateBackup(ctx context.Context, req *CreateBackupRequestBody) (r *BackupResource, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDisk implements create-disk operation.
//
// 云硬盘创建在所选硬盘类型所属的可用区，云服务器必须位于同一可用区才能挂载。因此选定硬盘类型即确定了可用区。.
//
// POST /api/v1/disks
func (UnimplementedHandler) CreateDisk(ctx context.Context, req *CreateDiskRequestBody) (r *DiskResource, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePort implements create-port operation.
//
// 创建出的网卡尚未挂载到任何云服务器。主网卡不由本接口创建，它随云服务器一并创建。.
//
// POST /api/v1/ports
func (UnimplementedHandler) CreatePort(ctx context.Context, req *CreatePortRequestBody) (r *PortResource, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePrivateImage implements create-private-image operation.
//
// 依据云服务器的系统盘制作，数据盘不包含在内。制作出的镜像可用于创建云服务器或重装系统，并在源云服务器释放后继续可用。
//
// 镜像内容取自开始制作的那一刻，此后对云服务器的改动不会包含在内。
//
// 制作分两个阶段，请轮询查看接口：
//
//   - `provisioning`
//     正在读取系统盘，通常数十秒。此阶段云服务器可以继续使用，但为保证一致性建议先关机。
//   - `uploading`
//     已与系统盘无关，此时即可开机，无需等待制作完成。该阶段耗时与系统盘容量成正比，20
//     GB 约需 3 分钟。
//
// 运行中的云服务器其文件系统可能处于写入中间状态，制作出的镜像等同于一次断电后的磁盘内容。对一致性有要求时，请在开始制作前关机，并在状态变为
// `uploading` 后开机。
//
// 制作期间该云服务器可以正常启停与使用，但无法释放。.
//
// POST /api/v1/private-images
func (UnimplementedHandler) CreatePrivateImage(ctx context.Context, req *CreatePrivateImageRequestBody) (r *PrivateImageResource, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePrivateNetwork implements create-private-network operation.
//
// 同时创建一张网络、一台路由器和一个默认安全组。默认安全组拒绝全部入站流量、放行全部出站流量。.
//
// POST /api/v1/private-networks
func (UnimplementedHandler) CreatePrivateNetwork(ctx context.Context, req *CreatePrivateNetworkRequestBody) (r *PrivateNetworkResource, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateRoute implements create-route operation.
//
// 以下三种会导致网络中断的写法会被拒绝：目的网段为
// 0.0.0.0/0（覆盖默认路由，所有公网 IP
// 立即失效）、目的网段为某个子网自身（覆盖直连路由）、下一跳为某个子网的网关（指回路由器自身）。.
//
// POST /api/v1/private-networks/{privateNetworkId}/routes
func (UnimplementedHandler) CreateRoute(ctx context.Context, req *CreateRouteRequestBody, params CreateRouteParams) (r *RouteResource, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSecurityGroup implements create-security-group operation.
//
// 新建的安全组带有一条规则：放行 ICMP 需要分片（type 3 code
// 4）。缺少该规则会导致路径 MTU
// 发现失败，表现为连接建立后传输大数据包时卡住。.
//
// POST /api/v1/security-groups
func (UnimplementedHandler) CreateSecurityGroup(ctx context.Context, req *CreateSecurityGroupRequestBody) (r *SecurityGroupResource, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSecurityGroupRule implements create-security-group-rule operation.
//
// 重复添加同一条规则会被拒绝。判重时 `0.0.0.0/0`、`::/0` 与留空视为等同。.
//
// POST /api/v1/security-groups/{securityGroupId}/rules
func (UnimplementedHandler) CreateSecurityGroupRule(ctx context.Context, req *CreateSecurityRuleRequestBody, params CreateSecurityGroupRuleParams) (r *SecurityRuleResource, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSnapshot implements create-snapshot operation.
//
// 运行中云服务器上挂载的云硬盘同样可以创建快照。快照记录的是某一时刻的块设备状态，文件系统层面可能不一致，重要数据建议先在云服务器内执行
// sync。
//
// 系统盘的快照不能用于回滚该系统盘：回滚要求先从云服务器上卸载，而系统盘不可卸载。它可用于创建一块新的数据盘。需要保留并恢复整个系统时，请使用自制镜像；需要可跨可用区、且在云硬盘删除后仍可恢复的副本时，请使用备份。.
//
// POST /api/v1/snapshots
func (UnimplementedHandler) CreateSnapshot(ctx context.Context, req *CreateSnapshotRequestBody) (r *SnapshotResource, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSubnet implements create-subnet operation.
//
// 创建子网.
//
// POST /api/v1/private-networks/{privateNetworkId}/subnets
func (UnimplementedHandler) CreateSubnet(ctx context.Context, req *CreateSubnetRequestBody, params CreateSubnetParams) (r *SubnetResource, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteBackup implements delete-backup operation.
//
// 与源云硬盘无关，源云硬盘是否存在都不影响删除。.
//
// DELETE /api/v1/backups/{backupId}
func (UnimplementedHandler) DeleteBackup(ctx context.Context, params DeleteBackupParams) error {
	return ht.ErrNotImplemented
}

// DeleteDisk implements delete-disk operation.
//
// 云硬盘处于挂载状态，或仍存在基于它创建的快照时，删除会被拒绝。.
//
// DELETE /api/v1/disks/{diskId}
func (UnimplementedHandler) DeleteDisk(ctx context.Context, params DeleteDiskParams) error {
	return ht.ErrNotImplemented
}

// DeleteInstance implements delete-instance operation.
//
// 系统盘随云服务器一并删除，基于系统盘创建的快照也会一并删除。数据盘会被卸载并保留，其快照与备份不受影响。主网卡随云服务器一并释放。
//
// 正在制作镜像的云服务器无法释放，请等待制作完成或先删除该镜像。.
//
// DELETE /api/v1/instances/{instanceId}
func (UnimplementedHandler) DeleteInstance(ctx context.Context, params DeleteInstanceParams) error {
	return ht.ErrNotImplemented
}

// DeletePort implements delete-port operation.
//
// 主网卡不可单独删除，它随云服务器一并释放。仍挂载在云服务器上的网卡也无法删除。.
//
// DELETE /api/v1/ports/{portId}
func (UnimplementedHandler) DeletePort(ctx context.Context, params DeletePortParams) error {
	return ht.ErrNotImplemented
}

// DeletePrivateImage implements delete-private-image operation.
//
// 仍有云服务器由该镜像创建时，删除会被拒绝：这些云服务器需要它才能重装系统。
//
// 制作尚未完成的镜像也可以删除，制作会被终止。.
//
// DELETE /api/v1/private-images/{privateImageId}
func (UnimplementedHandler) DeletePrivateImage(ctx context.Context, params DeletePrivateImageParams) error {
	return ht.ErrNotImplemented
}

// DeletePrivateNetwork implements delete-private-network operation.
//
// 其中仍有云服务器或网卡时，释放会被拒绝。IPv6、路由器与安全组随之一并释放。.
//
// DELETE /api/v1/private-networks/{privateNetworkId}
func (UnimplementedHandler) DeletePrivateNetwork(ctx context.Context, params DeletePrivateNetworkParams) error {
	return ht.ErrNotImplemented
}

// DeleteRoute implements delete-route operation.
//
// 删除静态路由.
//
// DELETE /api/v1/private-networks/{privateNetworkId}/routes/{routeId}
func (UnimplementedHandler) DeleteRoute(ctx context.Context, params DeleteRouteParams) error {
	return ht.ErrNotImplemented
}

// DeleteSecurityGroup implements delete-security-group operation.
//
// 默认安全组不可删除，它随私有网络一并释放。仍被网卡引用的安全组也无法删除。.
//
// DELETE /api/v1/security-groups/{securityGroupId}
func (UnimplementedHandler) DeleteSecurityGroup(ctx context.Context, params DeleteSecurityGroupParams) error {
	return ht.ErrNotImplemented
}

// DeleteSecurityGroupRule implements delete-security-group-rule operation.
//
// 删除安全组规则.
//
// DELETE /api/v1/security-groups/{securityGroupId}/rules/{ruleId}
func (UnimplementedHandler) DeleteSecurityGroupRule(ctx context.Context, params DeleteSecurityGroupRuleParams) error {
	return ht.ErrNotImplemented
}

// DeleteSnapshot implements delete-snapshot operation.
//
// 删除快照.
//
// DELETE /api/v1/snapshots/{snapshotId}
func (UnimplementedHandler) DeleteSnapshot(ctx context.Context, params DeleteSnapshotParams) error {
	return ht.ErrNotImplemented
}

// DeleteSubnet implements delete-subnet operation.
//
// 该子网中仍有网卡，或仍有静态路由的下一跳落在该网段内时，删除会被拒绝。.
//
// DELETE /api/v1/private-networks/{privateNetworkId}/subnets/{subnetId}
func (UnimplementedHandler) DeleteSubnet(ctx context.Context, params DeleteSubnetParams) error {
	return ht.ErrNotImplemented
}

// DetachDisk implements detach-disk operation.
//
// 请先在云服务器内卸载（umount）该设备再调用本接口，正在写入的文件系统被强制卸载会损坏数据。.
//
// DELETE /api/v1/instances/{instanceId}/disks/{diskId}
func (UnimplementedHandler) DetachDisk(ctx context.Context, params DetachDiskParams) (r *DiskResource, _ error) {
	return r, ht.ErrNotImplemented
}

// DetachInstanceFloatingIP implements detach-instance-floating-ip operation.
//
// 解绑云服务器的公网 IP.
//
// DELETE /api/v1/instances/{instanceId}/floating-ips/{floatingIpId}
func (UnimplementedHandler) DetachInstanceFloatingIP(ctx context.Context, params DetachInstanceFloatingIPParams) (r *FloatingIPResource, _ error) {
	return r, ht.ErrNotImplemented
}

// DetachPort implements detach-port operation.
//
// 主网卡不可卸载，卸载后云服务器将失去网络地址。.
//
// DELETE /api/v1/instances/{instanceId}/ports/{portId}
func (UnimplementedHandler) DetachPort(ctx context.Context, params DetachPortParams) (r *PortResource, _ error) {
	return r, ht.ErrNotImplemented
}

// DisablePrivateNetworkIpv6 implements disable-private-network-ipv6 operation.
//
// 释放的前缀不会立即重新分配。.
//
// DELETE /api/v1/private-networks/{privateNetworkId}/ipv6
func (UnimplementedHandler) DisablePrivateNetworkIpv6(ctx context.Context, params DisablePrivateNetworkIpv6Params) error {
	return ht.ErrNotImplemented
}

// EnablePrivateNetworkIpv6 implements enable-private-network-ipv6 operation.
//
// 为该私有网络分配一段 IPv6
// 地址。地址由私有网络自动下发至云服务器，无需也无法单独申领，也不占用公网
// IPv4。
//
// 该私有网络尚未接入外网时会自动接入，无需单独操作。.
//
// POST /api/v1/private-networks/{privateNetworkId}/ipv6
func (UnimplementedHandler) EnablePrivateNetworkIpv6(ctx context.Context, params EnablePrivateNetworkIpv6Params) (r *IPv6ResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// GetBackup implements get-backup operation.
//
// 会实时查询备份的当前状态，因此比列表接口慢但更准确。轮询创建进度请使用本接口。.
//
// GET /api/v1/backups/{backupId}
func (UnimplementedHandler) GetBackup(ctx context.Context, params GetBackupParams) (r *BackupResource, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDisk implements get-disk operation.
//
// 会实时查询云硬盘的当前状态，因此比列表接口慢但更准确。.
//
// GET /api/v1/disks/{diskId}
func (UnimplementedHandler) GetDisk(ctx context.Context, params GetDiskParams) (r *DiskResource, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFloatingIP implements get-floating-ip operation.
//
// 查看公网 IP.
//
// GET /api/v1/floating-ips/{floatingIpId}
func (UnimplementedHandler) GetFloatingIP(ctx context.Context, params GetFloatingIPParams) (r *FloatingIPResource, _ error) {
	return r, ht.ErrNotImplemented
}

// GetInstance implements get-instance operation.
//
// 会实时查询云服务器的当前状态，因此比列表接口慢但更准确。轮询创建进度请使用本接口。.
//
// GET /api/v1/instances/{instanceId}
func (UnimplementedHandler) GetInstance(ctx context.Context, params GetInstanceParams) (r *InstanceResource, _ error) {
	return r, ht.ErrNotImplemented
}

// GetInstanceConsoleOutput implements get-instance-console-output operation.
//
// 云服务器启动过程与内核输出的原始文本。无法登录或远程控制台无输出时，应首先查看本接口。其中可查看启动停止于哪一步、系统盘是否正常挂载、初始化过程是否报错。
//
// 处于错误状态或已被平台停服的云服务器同样可以读取。.
//
// GET /api/v1/instances/{instanceId}/console-output
func (UnimplementedHandler) GetInstanceConsoleOutput(ctx context.Context, params GetInstanceConsoleOutputParams) (r *ConsoleOutputResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPrivateImage implements get-private-image operation.
//
// 轮询制作进度请使用本接口。status 为 error 时，failure 给出失败原因。.
//
// GET /api/v1/private-images/{privateImageId}
func (UnimplementedHandler) GetPrivateImage(ctx context.Context, params GetPrivateImageParams) (r *PrivateImageResource, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPrivateNetwork implements get-private-network operation.
//
// 查看私有网络.
//
// GET /api/v1/private-networks/{privateNetworkId}
func (UnimplementedHandler) GetPrivateNetwork(ctx context.Context, params GetPrivateNetworkParams) (r *PrivateNetworkResource, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPrivateNetworkIpv6 implements get-private-network-ipv6 operation.
//
// 查看私有网络的 IPv6.
//
// GET /api/v1/private-networks/{privateNetworkId}/ipv6
func (UnimplementedHandler) GetPrivateNetworkIpv6(ctx context.Context, params GetPrivateNetworkIpv6Params) (r *IPv6ResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSecurityGroup implements get-security-group operation.
//
// 查看安全组.
//
// GET /api/v1/security-groups/{securityGroupId}
func (UnimplementedHandler) GetSecurityGroup(ctx context.Context, params GetSecurityGroupParams) (r *SecurityGroupResource, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSnapshot implements get-snapshot operation.
//
// 查看快照.
//
// GET /api/v1/snapshots/{snapshotId}
func (UnimplementedHandler) GetSnapshot(ctx context.Context, params GetSnapshotParams) (r *SnapshotResource, _ error) {
	return r, ht.ErrNotImplemented
}

// LaunchInstance implements launch-instance operation.
//
// 必须在请求中设置密码：不设置时请求会被拒绝，否则创建出的云服务器将无法登录。密码可由平台生成，此时仅在本次响应中返回一次。
//
// `count` 可一次创建多台（最多 20 台），名称自动加 `-1`、`-2`
// 编号，所有云服务器共用同一个密码。响应中的 `instances`
// 始终是数组，单台创建时也是。
//
// 批量创建按顺序逐台进行。若中途失败（例如配额不足），已创建的云服务器会保留，响应中的
// `failure`
// 给出中止原因；第一台就失败时视为整次请求失败，不会创建任何云服务器。
//
// 镜像二选一：`image_id` 使用平台提供的镜像，`private_image_id`
// 使用自制镜像。两者都给或都不给都会被拒绝。
//
// 云服务器创建在机型所属的可用区。后续要挂载的云硬盘必须位于同一可用区。
//
// 接口返回时创建尚未完成（status 为 provisioning），请轮询 GET 确认结果。.
//
// POST /api/v1/instances
func (UnimplementedHandler) LaunchInstance(ctx context.Context, req *LaunchInstanceRequestBody) (r *LaunchInstanceResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAvailabilityZones implements list-availability-zones operation.
//
// 云硬盘与云服务器必须位于同一可用区才能挂载，创建前请确认所选可用区。.
//
// GET /api/v1/regions/{regionCode}/availability-zones
func (UnimplementedHandler) ListAvailabilityZones(ctx context.Context, params ListAvailabilityZonesParams) (r *ZoneListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListBackups implements list-backups operation.
//
// 列出备份.
//
// GET /api/v1/backups
func (UnimplementedHandler) ListBackups(ctx context.Context, params ListBackupsParams) (r *BackupListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDiskTypes implements list-disk-types operation.
//
// 列出在售硬盘类型.
//
// GET /api/v1/disk-types
func (UnimplementedHandler) ListDiskTypes(ctx context.Context, params ListDiskTypesParams) (r *DiskTypeListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDisks implements list-disks operation.
//
// 同时提供 region_code 与 availability_zone
// 时，只返回可挂载到该位置云服务器的云硬盘。.
//
// GET /api/v1/disks
func (UnimplementedHandler) ListDisks(ctx context.Context, params ListDisksParams) (r *DiskListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListFloatingIps implements list-floating-ips operation.
//
// 列出公网 IP.
//
// GET /api/v1/floating-ips
func (UnimplementedHandler) ListFloatingIps(ctx context.Context) (r *FloatingIPListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListImages implements list-images operation.
//
// Min_ram_mb 超过所选机型内存的镜像无法启动，请据此过滤可选项。.
//
// GET /api/v1/images
func (UnimplementedHandler) ListImages(ctx context.Context, params ListImagesParams) (r *ImageListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListInstanceDisks implements list-instance-disks operation.
//
// 列出云服务器已挂载的云硬盘.
//
// GET /api/v1/instances/{instanceId}/disks
func (UnimplementedHandler) ListInstanceDisks(ctx context.Context, params ListInstanceDisksParams) (r *DiskListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListInstancePorts implements list-instance-ports operation.
//
// 列出云服务器的网卡.
//
// GET /api/v1/instances/{instanceId}/ports
func (UnimplementedHandler) ListInstancePorts(ctx context.Context, params ListInstancePortsParams) (r *PortListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListInstanceTypes implements list-instance-types operation.
//
// 列出在售机型.
//
// GET /api/v1/instance-types
func (UnimplementedHandler) ListInstanceTypes(ctx context.Context, params ListInstanceTypesParams) (r *InstanceTypeListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListInstances implements list-instances operation.
//
// 列出云服务器.
//
// GET /api/v1/instances
func (UnimplementedHandler) ListInstances(ctx context.Context) (r *InstanceListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListOperationLogs implements list-operation-logs operation.
//
// 记录本项目内的每一次写操作：谁、在什么时候、对什么做了什么、成功还是失败。读取操作不记录。
//
// 平台代为执行的操作也在其中，但不显示具体执行人，`by_platform` 为
// true。例如欠费停机、违规封禁：需要知道机器何时被平台停止，但执行人属于平台内部信息。
//
// 密码一类的字段在写入时即被替换为占位符，不会出现在 `payload` 中。.
//
// GET /api/v1/operation-logs
func (UnimplementedHandler) ListOperationLogs(ctx context.Context, params ListOperationLogsParams) (r *OperationLogListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPorts implements list-ports operation.
//
// 列出网卡.
//
// GET /api/v1/ports
func (UnimplementedHandler) ListPorts(ctx context.Context) (r *PortListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPrivateImages implements list-private-images operation.
//
// 列出自制镜像.
//
// GET /api/v1/private-images
func (UnimplementedHandler) ListPrivateImages(ctx context.Context, params ListPrivateImagesParams) (r *PrivateImageListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPrivateNetworks implements list-private-networks operation.
//
// 列出私有网络.
//
// GET /api/v1/private-networks
func (UnimplementedHandler) ListPrivateNetworks(ctx context.Context, params ListPrivateNetworksParams) (r *PrivateNetworkListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListRegions implements list-regions operation.
//
// 列出可用的地区.
//
// GET /api/v1/regions
func (UnimplementedHandler) ListRegions(ctx context.Context) (r *RegionListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListRoutes implements list-routes operation.
//
// 列出静态路由.
//
// GET /api/v1/private-networks/{privateNetworkId}/routes
func (UnimplementedHandler) ListRoutes(ctx context.Context, params ListRoutesParams) (r *RouteListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListSecurityGroupRules implements list-security-group-rules operation.
//
// 列出安全组规则.
//
// GET /api/v1/security-groups/{securityGroupId}/rules
func (UnimplementedHandler) ListSecurityGroupRules(ctx context.Context, params ListSecurityGroupRulesParams) (r *SecurityRuleListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListSecurityGroups implements list-security-groups operation.
//
// 列出安全组.
//
// GET /api/v1/security-groups
func (UnimplementedHandler) ListSecurityGroups(ctx context.Context, params ListSecurityGroupsParams) (r *SecurityGroupListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListSnapshots implements list-snapshots operation.
//
// 列出快照.
//
// GET /api/v1/snapshots
func (UnimplementedHandler) ListSnapshots(ctx context.Context, params ListSnapshotsParams) (r *SnapshotListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ListSubnets implements list-subnets operation.
//
// IPv6 子网也在返回结果中，ip_version 为 6。它在启用 IPv6
// 时自动创建，不可单独删除。.
//
// GET /api/v1/private-networks/{privateNetworkId}/subnets
func (UnimplementedHandler) ListSubnets(ctx context.Context, params ListSubnetsParams) (r *SubnetListResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// OpenInstanceConsole implements open-instance-console operation.
//
// 在浏览器中直接操作云服务器，无需网络可达，适用于网络配置失误导致无法登录的情况。
//
// 返回的地址一次性使用，数分钟后失效。请勿缓存，每次使用前重新获取。.
//
// POST /api/v1/instances/{instanceId}/console
func (UnimplementedHandler) OpenInstanceConsole(ctx context.Context, params OpenInstanceConsoleParams) (r *ConsoleResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// RebuildInstance implements rebuild-instance operation.
//
// 系统盘数据将被清除且无法恢复。 已挂载的数据盘不受影响。.
//
// POST /api/v1/instances/{instanceId}/rebuild
func (UnimplementedHandler) RebuildInstance(ctx context.Context, req *RebuildInstanceRequestBody, params RebuildInstanceParams) (r *RebuildInstanceResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ReleaseFloatingIP implements release-floating-ip operation.
//
// 地址释放后进入冷却期才会重新分配，以免仍指向它的 DNS
// 记录和访问白名单立即失效。因此释放后的短时间内无法重新申领同一个地址，请谨慎操作。.
//
// DELETE /api/v1/floating-ips/{floatingIpId}
func (UnimplementedHandler) ReleaseFloatingIP(ctx context.Context, params ReleaseFloatingIPParams) error {
	return ht.ErrNotImplemented
}

// RenameBackup implements rename-backup operation.
//
// 重命名备份.
//
// PATCH /api/v1/backups/{backupId}
func (UnimplementedHandler) RenameBackup(ctx context.Context, req *RenameBackupRequestBody, params RenameBackupParams) (r *BackupResource, _ error) {
	return r, ht.ErrNotImplemented
}

// RenameDisk implements rename-disk operation.
//
// 仅可修改名称。容量请使用扩容接口，类型与可用区不可修改。.
//
// PATCH /api/v1/disks/{diskId}
func (UnimplementedHandler) RenameDisk(ctx context.Context, req *RenameDiskRequestBody, params RenameDiskParams) (r *DiskResource, _ error) {
	return r, ht.ErrNotImplemented
}

// RenameInstance implements rename-instance operation.
//
// 仅修改显示名称。云服务器内的主机名不变，它等于云服务器 id。.
//
// PATCH /api/v1/instances/{instanceId}
func (UnimplementedHandler) RenameInstance(ctx context.Context, req *RenameInstanceRequestBody, params RenameInstanceParams) (r *InstanceResource, _ error) {
	return r, ht.ErrNotImplemented
}

// RenamePrivateImage implements rename-private-image operation.
//
// 重命名自制镜像.
//
// PATCH /api/v1/private-images/{privateImageId}
func (UnimplementedHandler) RenamePrivateImage(ctx context.Context, req *RenamePrivateImageRequestBody, params RenamePrivateImageParams) (r *PrivateImageResource, _ error) {
	return r, ht.ErrNotImplemented
}

// RenamePrivateNetwork implements rename-private-network operation.
//
// 仅修改显示名称。网段、路由与外网网关均不可修改。.
//
// PATCH /api/v1/private-networks/{privateNetworkId}
func (UnimplementedHandler) RenamePrivateNetwork(ctx context.Context, req *RenamePrivateNetworkRequestBody, params RenamePrivateNetworkParams) (r *PrivateNetworkResource, _ error) {
	return r, ht.ErrNotImplemented
}

// RenameSecurityGroup implements rename-security-group operation.
//
// 仅可修改名称，规则请用规则接口。.
//
// PATCH /api/v1/security-groups/{securityGroupId}
func (UnimplementedHandler) RenameSecurityGroup(ctx context.Context, req *RenameSecurityGroupRequestBody, params RenameSecurityGroupParams) (r *SecurityGroupResource, _ error) {
	return r, ht.ErrNotImplemented
}

// RenameSnapshot implements rename-snapshot operation.
//
// 重命名快照.
//
// PATCH /api/v1/snapshots/{snapshotId}
func (UnimplementedHandler) RenameSnapshot(ctx context.Context, req *RenameSnapshotRequestBody, params RenameSnapshotParams) (r *SnapshotResource, _ error) {
	return r, ht.ErrNotImplemented
}

// ResetInstancePassword implements reset-instance-password operation.
//
// 在不重启的情况下改掉 root 的密码，云服务器必须处于运行中。
//
// 并非所有镜像都支持：镜像列表中 `supports_password_reset` 为 false
// 的镜像做不到，此时只能通过重装系统设置新密码，而重装会清除系统盘上的全部数据。
//
// 镜像标记为支持、但云服务器内相应组件已被卸载或停止时，本接口同样会被拒绝。.
//
// POST /api/v1/instances/{instanceId}/password
func (UnimplementedHandler) ResetInstancePassword(ctx context.Context, req *ResetPasswordRequestBody, params ResetInstancePasswordParams) (r *ResetPasswordResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ResizeDisk implements resize-disk operation.
//
// 容量只能增加，不支持缩容。扩容完成后需在云服务器内自行扩展文件系统。.
//
// POST /api/v1/disks/{diskId}/resize
func (UnimplementedHandler) ResizeDisk(ctx context.Context, req *ResizeDiskRequestBody, params ResizeDiskParams) (r *DiskResource, _ error) {
	return r, ht.ErrNotImplemented
}

// ResizeInstance implements resize-instance operation.
//
// 只能变更为同一地区、同一可用区的机型，否则已挂载的云硬盘无法随之迁移。
//
// 变配分两步：本接口下发后云服务器会在新规格上重新启动，状态变为
// `resize_verifying`，此时必须调用确认或回滚接口。目标机型在确认前记在
// `pending_instance_type_id` 上，`instance_type_id` 仍为当前生效并计费的机型。
//
// 未确认期间新旧两份规格同时占用资源。 请在状态变为 `resize_verifying`
// 后尽快确认。.
//
// POST /api/v1/instances/{instanceId}/resize
func (UnimplementedHandler) ResizeInstance(ctx context.Context, req *ResizeInstanceRequestBody, params ResizeInstanceParams) (r *InstanceResource, _ error) {
	return r, ht.ErrNotImplemented
}

// RestoreBackup implements restore-backup operation.
//
// 恢复到一块新建的云硬盘上，源云硬盘不受影响，也不要求它仍然存在。
//
// 目标硬盘类型可位于本地区的其他可用区，容量不能小于备份。恢复完成前该云硬盘不可挂载，请轮询云硬盘查看接口。.
//
// POST /api/v1/backups/{backupId}/restore
func (UnimplementedHandler) RestoreBackup(ctx context.Context, req *RestoreBackupRequestBody, params RestoreBackupParams) (r *DiskResource, _ error) {
	return r, ht.ErrNotImplemented
}

// RevertDisk implements revert-disk operation.
//
// 将云硬盘的内容恢复到创建该快照的时刻。该时刻之后写入的数据全部丢失，且无法撤销。
//
// 三项限制：只能回滚到该云硬盘最新的一个快照；云硬盘必须先从云服务器上卸载；创建快照后扩容过的云硬盘不能回滚。需要回到更早的时刻，或需要保留现有云硬盘时，请改用由快照创建一块新的云硬盘。
//
// 接口返回时回滚尚未完成，请轮询查看接口。.
//
// POST /api/v1/disks/{diskId}/revert
func (UnimplementedHandler) RevertDisk(ctx context.Context, req *RevertDiskRequestBody, params RevertDiskParams) (r *DiskResource, _ error) {
	return r, ht.ErrNotImplemented
}

// RevertInstanceResize implements revert-instance-resize operation.
//
// 云服务器回到原规格，`pending_instance_type_id`
// 被丢弃，计费不受本次变配影响。.
//
// POST /api/v1/instances/{instanceId}/resize/revert
func (UnimplementedHandler) RevertInstanceResize(ctx context.Context, params RevertInstanceResizeParams) (r *InstanceResource, _ error) {
	return r, ht.ErrNotImplemented
}

// SetFloatingIPBandwidth implements set-floating-ip-bandwidth operation.
//
// 出入两个方向同时限速。仅限制出方向无法防止入方向流量打满上联带宽。.
//
// PUT /api/v1/floating-ips/{floatingIpId}/bandwidth
func (UnimplementedHandler) SetFloatingIPBandwidth(ctx context.Context, req *SetBandwidthRequestBody, params SetFloatingIPBandwidthParams) (r *FloatingIPResource, _ error) {
	return r, ht.ErrNotImplemented
}

// SuggestSubnetCidr implements suggest-subnet-cidr operation.
//
// 返回的只是建议值，创建子网时仍会重新校验。用于避免手工计算下一个空闲网段时出错。.
//
// GET /api/v1/private-networks/{privateNetworkId}/subnets/next-free-cidr
func (UnimplementedHandler) SuggestSubnetCidr(ctx context.Context, params SuggestSubnetCidrParams) (r *NextFreeCidrResponseBody, _ error) {
	return r, ht.ErrNotImplemented
}

// UnbindFloatingIP implements unbind-floating-ip operation.
//
// 地址仍归本项目持有，只是不再指向任何网卡。.
//
// DELETE /api/v1/floating-ips/{floatingIpId}/binding
func (UnimplementedHandler) UnbindFloatingIP(ctx context.Context, params UnbindFloatingIPParams) (r *FloatingIPResource, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
